### ISSUE TITLE
Build OLM bundle on every merge

### ISSUE THREAD

**Issue by hasheddan** [upbound/universal-crossplane#125]
### What problem are you facing?

Currently, building the OLM bundle is a manual process. While builds should be reproducible from source, we are not currently building until it is actually time to publish a version.

### How could Universal Crossplane help solve your problem?

UXP CI pipelines should build and publish OLM bundles alongside other artifacts.

**Comment by muvaf** [comment]
By publishing, you mean pushing the OLM bundle image to a registry, right?

**Comment by hasheddan** [comment]
@muvaf I was actually planning on just publishing a tarball of the produced `bundle` source since IIUC that is what we submit to the community-operators repo and the machinery there builds the image.

**Comment by hasheddan** [comment]
This would update the flow in the short-term to just be downloading the bundle and opening a PR to community-operators with its contents, and in the long-term that PR could automatically be opened.

**Comment by muvaf** [comment]
I think it depends on what we want from those builds. If it's for usage by others, then pushing the image to registry makes more sense because that's the usable artifact. However, users can't directly use it, they have to [build a new catalog](https://github.com/upbound/universal-crossplane/blob/main/cluster/olm/README.md#publish) including that image and then consume it from there. So it's still not a great experience, as opposed to Helm CLI.

If it's for pushing to community-operators repo, we should do it for `release-*` branches but I'm not sure opening a PR at every merge on `main` would be feasible since each PR requires a review. But they have the notion of stable/beta channels, so if there is a way to automatically push somewhere and have it ready in a channel like `main` or `alpha` (other than `stable`), then I think it's more feasible to do.

**Comment by hasheddan** [comment]
> If it's for usage by others, then pushing the image to registry makes more sense because that's the usable artifact.

Though I don't think the image we built would be used for anything but testing, it might be useful to build and push it anyway. That being said, I am much more concerned about the source `bundle`.

> I'm not sure opening a PR at every merge on main would be feasible since each PR requires a review

Sorry I'm not suggesting opening the PR on every merge, just building the artifact and putting it in https://releases.upbound.io/universal-crossplane/. Like other artifacts, they go into the appropriate channel subdirectories there with their version. This is similar to what I do in the CLI with debs and rpms https://cli.upbound.io/p?prefix=stable/v0.2.0/
