### ISSUE TITLE
Consider treating `-up.X` as a release version when evaluating Crossplane constraints for package

### ISSUE THREAD

**Issue by hasheddan** [upbound/universal-crossplane#301]
### What problem are you facing?

Crossplane will refuse to install packages that don't specify Crossplane constraints with `-0` if the Crossplane version is not a release version. However, because UXP uses a `-up.X` versioning scheme, all releases are considered non-release versions.

### How could Upbound help solve your problem?

We should consider special-casing `-up.X` versions as release versions and allowing install of packages that restrict to only release versions.

**Comment by turkenh** [comment]
I believe this would a package manager change in [upbound/crossplane](https://github.com/upbound/crossplane), at the lines where we check the [XP version](https://github.com/crossplane/crossplane/blob/33c8a2c52f6465513a3e1873613446b307e3356b/internal/xpkg/lint.go#L92).

**Comment by turkenh** [comment]
It looks like we have indeed fixed this with https://github.com/upbound/crossplane/pull/17, but somehow missed including this in the recent release branches of upbound/crossplane due to the existing manual release process and branch preparation.

@phisco is working on improving and automating our release process and catched this and opened a fix https://github.com/upbound/crossplane/pull/84 to include it in the upcoming v1.12 release. 

So, we will no longer need a special treatment with xp version dependencies as mentioned in this issue.

**Comment by turkenh** [comment]
We just released [v1.12.1-up.1](https://github.com/upbound/universal-crossplane/releases/tag/v1.12.1-up.1) with the backported fix. 

Crossplane dependency should now work with UXP in the same way as upstream, for example:

```
spec:
  crossplane:
    version: ">=v1.12.0"
```
