### ISSUE TITLE
local.down should delete the self-hosted control plane

### ISSUE THREAD

**Issue by muvaf** [upbound/universal-crossplane#45]
It deletes my kind cluster but the control plane is left there and when you try to connect to it with a new kind cluster it says:
```
upbound-agent: error: failed to create new agent proxy: failed to connect NATS: new token request failed with 400 Bad Request - {
                        "message": "this control plane is registered for another kubernetes cluster"
                      }
```

`make local.down` should delete the control plane it created so that experience is smoother.

**Comment by turkenh** [comment]
See https://github.com/upbound/universal-crossplane/pull/152#discussion_r655656951

There are some technical limitations with doing this at the moment since we don't actually delete components one by one during `make local.down` rather just delete the kind cluster. This is different than deployment where we could implement pre-deploy, post-deploy hooks.  We could consider introducing a global `pre-down` hook though.

**Comment by jeanduplessis** [comment]
Closing as no longer relevant
